### ISSUE TITLE
.NET 9

### ISSUE THREAD

**Issue by pjastrzebskiman** [marius-bughiu/Plugin.AdMob#14]
Hello! Are you planning to release a version compatible with .NET 9 in the near future?

**Comment by Saccomani** [comment]
I am trying to use, when add the package in android show the error below!

Error in obj/Debug/net9.0-android/lp/233/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class:
Type androidx.work.CoroutineWorker$startWork$1 is defined multiple times: obj/Debug/net9.0-android/lp/233/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class, obj/Debug/net9.0-android/lp/252/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class
Compilation failed
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj/Debug/net9.0-android/lp/233/jl/classes.jar
androidx/work/CoroutineWorker$startWork$1.class
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:131)
	at com.android.tools.r8.D8.main(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:5)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj/Debug/net9.0-android/lp/233/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class
	at Version.fakeStackEntry(Version_8.5.35.java:0)
	at com.android.tools.r8.T.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:5)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:82)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:32)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:31)
	at com.android.tools.r8.internal.to.b(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:2)
	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:41)
	at com.android.tools.r8.D8.b(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:13)
	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:39)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:118)
	... 1 more
Caused by: com.android.tools.r8.internal.g: Type androidx.work.CoroutineWorker$startWork$1 is defined multiple times: obj/Debug/net9.0-android/lp/233/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class, obj/Debug/net9.0-android/lp/252/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class
	at com.android.tools.r8.internal.x50.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:21)
	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:54)
	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2056)
	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:6)
	at com.android.tools.r8.graph.p4$a.d(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:6)
	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:95)
	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:44)
	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:9)
	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:44)
	at com.android.tools.r8.D8.d(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:17)
	at com.android.tools.r8.D8.c(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:73)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:28)
	... 6 more
O diretório 'obj/Debug/net9.0-android/lp/233' é de 'androidx.work.work-runtime.aar'.
O diretório 'obj/Debug/net9.0-android/lp/252' é de 'androidx.work.work-runtime-ktx.aar'.

**Comment by marius-bughiu** [comment]
@pjastrzebskiman, @Saccomani, could you give it a try with the latest beta package and let me know if that fixes your problems? Lastest version targets .NET 9 as well and should pull the proper dependencies.

**Comment by Saccomani** [comment]
> [@pjastrzebskiman](https://github.com/pjastrzebskiman), [@Saccomani](https://github.com/Saccomani), could you give it a try with the latest beta package and let me know if that fixes your problems? Lastest version targets .NET 9 as well and should pull the proper dependencies.

the same error, in android.

I having the same error in android:

  Error in obj/Debug/net9.0-android/lp/232/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class:
Type androidx.work.CoroutineWorker$startWork$1 is defined multiple times: obj/Debug/net9.0-android/lp/232/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class, obj/Debug/net9.0-android/lp/251/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class
Compilation failed
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj/Debug/net9.0-android/lp/232/jl/classes.jar
androidx/work/CoroutineWorker$startWork$1.class
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:131)
	at com.android.tools.r8.D8.main(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:5)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: obj/Debug/net9.0-android/lp/232/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class
	at Version.fakeStackEntry(Version_8.5.35.java:0)
	at com.android.tools.r8.T.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:5)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:82)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:32)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:31)
	at com.android.tools.r8.internal.to.b(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:2)
	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:41)
	at com.android.tools.r8.D8.b(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:13)
	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:39)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:118)
	... 1 more
Caused by: com.android.tools.r8.internal.g: Type androidx.work.CoroutineWorker$startWork$1 is defined multiple times: obj/Debug/net9.0-android/lp/232/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class, obj/Debug/net9.0-android/lp/251/jl/classes.jar:androidx/work/CoroutineWorker$startWork$1.class
	at com.android.tools.r8.internal.x50.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:21)
	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:54)
	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2056)
	at com.android.tools.r8.internal.LY.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:6)
	at com.android.tools.r8.graph.p4$a.d(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:6)
	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:95)
	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:44)
	at com.android.tools.r8.dex.c.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:9)
	at com.android.tools.r8.D8.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:44)
	at com.android.tools.r8.D8.d(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:17)
	at com.android.tools.r8.D8.c(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:73)
	at com.android.tools.r8.internal.to.a(R8_8.5.35_9c55004e7c41a17b1ed47c4e1952cb6778b3dac6afb6afc113a2737c3cde13e0:28)
	... 6 more
O diretório 'obj/Debug/net9.0-android/lp/232' é de 'androidx.work.work-runtime.aar'.
O diretório 'obj/Debug/net9.0-android/lp/251' é de 'androidx.work.work-runtime-ktx.aar'.

**Comment by Saccomani** [comment]
i have the following packages in my csproj

`
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>Namoridos</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<MauiVersion>9.0.30</MauiVersion>
		
		<ApplicationTitle>Namoridos</ApplicationTitle>
		<ApplicationId>br.com.fibonapps.xxx</ApplicationId>
		<ApplicationDisplayVersion>1.19</ApplicationDisplayVersion>
        <ApplicationVersion>2615</ApplicationVersion>
		<AndroidVersionCode>2615</AndroidVersionCode>
		        
    
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>

        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
        
	</PropertyGroup>


	
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
		<UseInterpreter>true</UseInterpreter>
		<MtouchLink>SdkOnly</MtouchLink>
		<MtouchHttpClientHandler>HttpClientHandler</MtouchHttpClientHandler>
		<MtouchFloat32>true</MtouchFloat32>
		<MtouchNoSymbolStrip>true</MtouchNoSymbolStrip>
		<MtouchFastDev>true</MtouchFastDev>
		<OptimizePNGs>true</OptimizePNGs>
		<AndroidLinkTool>r8</AndroidLinkTool>
	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
		<MtouchInterpreter>-all</MtouchInterpreter>
	</PropertyGroup>

	<ItemGroup>
		
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#2B003A" />
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#FFFFFF" BaseSize="400,320" />
		<MauiImage Include="Resources\Images\*" />
		<MauiFont Include="Resources\Fonts\*" />
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="10.0.0" />
		<PackageReference Include="CommunityToolkit.Maui.Markup" Version="5.1.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="InputKit.Maui" Version="4.5.0" />
		<PackageReference Include="Gamefy" Version="1.0.32" />
		<PackageReference Include="Gamefy.Domain" Version="1.0.32" />
		<PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="8.1.0-preview" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.30" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.30" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.1" />
		<PackageReference Include="OneSignalSDK.DotNet" Version="5.2.1" />
		<PackageReference Include="FFImageLoading.Maui" Version="1.2.7" />

		<PackageReference Include="Plugin.Maui.ImageCropper" Version="1.1.4" />
		<PackageReference Include="Mopups" Version="1.3.2" />
		
		
		<PackageReference Include="Sentry.Maui" Version="5.0.0" />
		<PackageReference Include="SkiaSharp.Extended" Version="2.0.0" />
		<PackageReference Include="SkiaSharp.Views.Maui.Core" Version="2.88.9" />
		<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.9" />
		<PackageReference Include="The49.Maui.BottomSheet" Version="8.0.3" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.1" />
		<PackageReference Include="Refractored.MvvmHelpers" Version="1.6.2" />

</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">

		<PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.8.5.1" />
		<PackageReference Include="Xamarin.Firebase.Analytics" Version="122.1.2.1" />
		<PackageReference Include="Xamarin.Firebase.Core" Version="121.1.1.12" />
		<PackageReference Include="Xamarin.GooglePlayServices.Measurement.Api" Version="122.1.2.1" />
	</ItemGroup>
</Project>

`

**Comment by marius-bughiu** [comment]
@Saccomani, I've tested with your list of dependencies and I'm not having any trouble building and running such a project on my side. Did you try a clean build? If you did, could you maybe provide a sample project reproducing the issue?

I've created a test branch where I modified the net9 sample project to include your dependencies: https://github.com/marius-bughiu/Plugin.AdMob/tree/test/dependencies, you can start from that. 

The net9 sample project is here: https://github.com/marius-bughiu/Plugin.AdMob/blob/test/dependencies/samples/Foo.Bar.SampleApp.Net9/Foo.Bar.SampleApp.Net9.csproj

**Comment by jcsawyer** [comment]
```
O diretório 'obj/Debug/net9.0-android/lp/232' é de 'androidx.work.work-runtime.aar'.
O diretório 'obj/Debug/net9.0-android/lp/251' é de 'androidx.work.work-runtime-ktx.aar'.
```
Suggests you may be pulling two versions of a package in transitively (or have them cached somewhere).
You could try doing a `nuget locals all -clear` and deleting your `obj`/`bin` dirs and running a restore then re-build.

If that doesn't help, you could try pulling in which ever package(s) directly - I suspect you may need to try something like:

```
<PackageReference Include="Xamarin.AndroidX.Work.Work.Runtime.Ktx" Version="2.10.0.3" />
```

**Comment by MoayadMyro1** [comment]
How to solve this issue 
Detected package version outside of dependency constraint: Xamarin.AndroidX.Lifecycle.Service 2.8.5.1 requires Xamarin.AndroidX.Lifecycle.Runtime (>= 2.8.5.1 && < 2.8.6) but version Xamarin.AndroidX.Lifecycle.Runtime 2.8.7.1 was resolved.

**Comment by marius-bughiu** [comment]
@MoayadMyro1, you should update `Xamarin.AndroidX.Lifecycle.Service` to `2.8.7.1` - https://www.nuget.org/packages/Xamarin.AndroidX.Lifecycle.Service/2.8.7.1#dependencies-body-tab

**Comment by Saccomani** [comment]
@marius-bughiu , the latest release, worked fine in android for me!! Thanks a lot for help-me. i will continue my tests ☺️

**Comment by marius-bughiu** [comment]
Closing this for now, and let's track any remaining issues separately.
